#ifdef RING_BLE_GATT_SERVER_TEST_DEFINE
#undef RING_BLE_GATT_SERVER_TEST_DEFINE
#endif

#ifdef RING_BLE_DEF_ADD_COMMAND
#undef RING_BLE_DEF_ADD_COMMAND
#define RING_BLE_GATT_SERVER_TEST_DEFINE(__arg1, __arg2)  AddCommand((char*)__arg1, __arg2)
#endif

#ifdef RING_BLE_DEF_CPP_WRAPPER
#undef RING_BLE_DEF_CPP_WRAPPER
#define RING_BLE_GATT_SERVER_TEST_DEFINE(__arg1, __arg2) static int __arg2(ParameterList_t *aParams) { return gGattSrvInst ? gGattSrvInst->__arg2(aParams) : BleApi::NOT_INITIALIZED_ERROR; }
#endif

RING_BLE_GATT_SERVER_TEST_DEFINE("CLEANUP",                         Cleanup);
RING_BLE_GATT_SERVER_TEST_DEFINE("INITIALIZE",                      Initialize);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYDEBUGZONEMASK",				QueryLocalRemoteDebugZoneMask);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETDEBUGZONEMASK",				SetLocalRemoteDebugZoneMask);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETDEBUGZONEMASKPID",				SetDebugZoneMaskPID);
RING_BLE_GATT_SERVER_TEST_DEFINE("SHUTDOWNSERVICE",                 ShutdownService);
RING_BLE_GATT_SERVER_TEST_DEFINE("REGISTEREVENTCALLBACK",           RegisterEventCallback);
RING_BLE_GATT_SERVER_TEST_DEFINE("UNREGISTEREVENTCALLBACK",			UnRegisterEventCallback);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYDEVICEPOWER",				QueryDevicePower);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETDEVICEPOWER",					SetDevicePower);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYLOCALDEVICEPROPERTIES",		QueryLocalDeviceProperties);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETLOCALDEVICENAME",				SetLocalDeviceName);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETLOCALCLASSOFDEVICE",			SetLocalClassOfDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETDISCOVERABLE",					SetDiscoverable);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETCONNECTABLE",					SetConnectable);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETPAIRABLE",                     SetPairable);
RING_BLE_GATT_SERVER_TEST_DEFINE("STARTDEVICEDISCOVERY",			StartDeviceDiscovery);
RING_BLE_GATT_SERVER_TEST_DEFINE("STOPDEVICEDISCOVERY",				StopDeviceDiscovery);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYREMOTEDEVICELIST",			QueryRemoteDeviceList);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYREMOTEDEVICEPROPERTIES",		QueryRemoteDeviceProperties);
RING_BLE_GATT_SERVER_TEST_DEFINE("ADDREMOTEDEVICE",					AddRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("DELETEREMOTEDEVICE",				DeleteRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("UPDATEREMOTEDEVICEAPPDATA",		UpdateRemoteDeviceApplicationData);
RING_BLE_GATT_SERVER_TEST_DEFINE("DELETEREMOTEDEVICES",				DeleteRemoteDevices);
RING_BLE_GATT_SERVER_TEST_DEFINE("PAIRWITHREMOTEDEVICE",			PairWithRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("CANCELPAIRWITHREMOTEDEVICE",		CancelPairWithRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("UNPAIRREMOTEDEVICE",				UnPairRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYREMOTEDEVICESERVICES",		QueryRemoteDeviceServices);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYREMOTEDEVICESERVICESUPPORTED",QueryRemoteDeviceServiceSupported);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYREMOTEDEVICESFORSERVICE",	QueryRemoteDevicesForService);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYREMOTEDEVICESERVICECLASSES",	QueryRemoteDeviceServiceClasses);
RING_BLE_GATT_SERVER_TEST_DEFINE("AUTHENTICATEREMOTEDEVICE",		AuthenticateRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("ENCRYPTREMOTEDEVICE",				EncryptRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("CONNECTWITHREMOTEDEVICE",			ConnectWithRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("DISCONNECTREMOTEDEVICE",			DisconnectRemoteDevice);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETREMOTEDEVICELINKACTIVE",		SetRemoteDeviceLinkActive);
RING_BLE_GATT_SERVER_TEST_DEFINE("CREATESDPRECORD",					CreateSDPRecord);
RING_BLE_GATT_SERVER_TEST_DEFINE("DELETESDPRECORD",					DeleteSDPRecord);
RING_BLE_GATT_SERVER_TEST_DEFINE("ADDSDPATTRIBUTE",					AddSDPAttribute);
RING_BLE_GATT_SERVER_TEST_DEFINE("DELETESDPATTRIBUTE",				DeleteSDPAttribute);
RING_BLE_GATT_SERVER_TEST_DEFINE("ENABLEBLUETOOTHDEBUG",			EnableBluetoothDebug);
RING_BLE_GATT_SERVER_TEST_DEFINE("REGISTERAUTHENTICATION",			RegisterAuthentication);
RING_BLE_GATT_SERVER_TEST_DEFINE("UNREGISTERAUTHENTICATION",		UnRegisterAuthentication);
RING_BLE_GATT_SERVER_TEST_DEFINE("PINCODERESPONSE",					PINCodeResponse);
RING_BLE_GATT_SERVER_TEST_DEFINE("PASSKEYRESPONSE",					PassKeyResponse);
RING_BLE_GATT_SERVER_TEST_DEFINE("USERCONFIRMATIONRESPONSE",		UserConfirmationResponse);
RING_BLE_GATT_SERVER_TEST_DEFINE("CHANGESIMPLEPAIRINGPARAMETERS",	ChangeSimplePairingParameters);
RING_BLE_GATT_SERVER_TEST_DEFINE("REGISTERGATTCALLBACK",			RegisterGATMEventCallback);
RING_BLE_GATT_SERVER_TEST_DEFINE("UNREGISTERGATTCALLBACK",			UnRegisterGATMEventCallback);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYGATTCONNECTIONS",			GATTQueryConnectedDevices);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETLOCALDEVICEAPPEARANCE",		SetLocalDeviceAppearance);
RING_BLE_GATT_SERVER_TEST_DEFINE("STARTADVERTISING",				StartAdvertising);
RING_BLE_GATT_SERVER_TEST_DEFINE("STOPADVERTISING",					StopAdvertising);
RING_BLE_GATT_SERVER_TEST_DEFINE("REGISTERSERVICE",					GATTRegisterService);
RING_BLE_GATT_SERVER_TEST_DEFINE("UNREGISTERSERVICE",				GATTUnRegisterService);
RING_BLE_GATT_SERVER_TEST_DEFINE("INDICATECHARACTERISTIC",			GATTIndicateCharacteristic);
RING_BLE_GATT_SERVER_TEST_DEFINE("NOTIFYCHARACTERISTIC",			GATTNotifyCharacteristic);
RING_BLE_GATT_SERVER_TEST_DEFINE("LISTCHARACTERISTICS",				ListCharacteristics);
RING_BLE_GATT_SERVER_TEST_DEFINE("LISTDESCRIPTORS",					ListDescriptors);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYPUBLISHEDSERVICES",			GATTQueryPublishedServices);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETADVERTISINGINTERVAL",			SetAdvertisingInterval);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETANDUPDATECONNECTIONANDSCANBLEPARAMETERS",SetAndUpdateConnectionAndScanBLEParameters);
RING_BLE_GATT_SERVER_TEST_DEFINE("SETAUTHENTICATEDPAYLOADTIMEOUT",	SetAuthenticatedPayloadTimeout);
RING_BLE_GATT_SERVER_TEST_DEFINE("QUERYAUTHENTICATEDPAYLOADTIMEOUT",QueryAuthenticatedPayloadTimeout);
RING_BLE_GATT_SERVER_TEST_DEFINE("ENABLESCONLY",					EnableSCOnly);
RING_BLE_GATT_SERVER_TEST_DEFINE("REGENERATEP256LOCALKEYS",			RegenerateP256LocalKeys);
RING_BLE_GATT_SERVER_TEST_DEFINE("OOBGENERATEPARAMETERS",			OOBGenerateParameters);
RING_BLE_GATT_SERVER_TEST_DEFINE("CHANGELEPAIRINGPARAMETERS",		ChangeLEPairingParameters);




































































