// HCI tools protoypes

void hcitool_rstat(int ctl, int hdev);
void hcitool_scan(int ctl, int hdev, char *opt);
void hcitool_le_addr(int hdev, char *opt);
void hcitool_le_adv(int hdev, char *opt);
void hcitool_no_le_adv(int hdev);
void hcitool_le_states(int hdev);
void hcitool_iac(int hdev, char *opt);
void hcitool_auth(int ctl, int hdev, char *opt);
void hcitool_encrypt(int ctl, int hdev, char *opt);
void hcitool_up(int ctl, int hdev);
void hcitool_down(int ctl, int hdev);
void hcitool_reset(int ctl, int hdev);
void hcitool_ptype(int ctl, int hdev, char *opt);
void hcitool_lp(int ctl, int hdev, char *opt);
void hcitool_lm(int ctl, int hdev, char *opt);
void hcitool_aclmtu(int ctl, int hdev, char *opt);
void hcitool_scomtu(int ctl, int hdev, char *opt);
void hcitool_features(int hdev);
void hcitool_name(int hdev, char *opt);
void hcitool_class(int hdev, char *opt);
void hcitool_voice(int hdev, char *opt);
void hcitool_delkey(int hdev, char *opt);
void hcitool_oob_data(int hdev);
void hcitool_commands(int hdev);
void hcitool_version(int hdev);
void hcitool_inq_tpl(int hdev, char *opt);
void hcitool_inq_mode(int hdev, char *opt);
void hcitool_inq_data(int hdev, char *opt);
void hcitool_inq_type(int hdev, char *opt);
void hcitool_inq_parms(int hdev, char *opt);
void hcitool_page_parms(int hdev, char *opt);
void hcitool_page_to(int hdev, char *opt);
void hcitool_afh_mode(int hdev, char *opt);
void hcitool_ssp_mode(int hdev, char *opt);
void hcitool_revision(int hdev);
void hcitool_block(int hdev, char *opt);
void hcitool_unblock(int hdev, char *opt);
